/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingWhatsappSuccessRouteImport } from './routes/onboarding.whatsapp.success'
import { Route as OnboardingWhatsappFailedRouteImport } from './routes/onboarding.whatsapp.failed'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWhatsappSuccessRoute =
  OnboardingWhatsappSuccessRouteImport.update({
    id: '/whatsapp/success',
    path: '/whatsapp/success',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingWhatsappFailedRoute =
  OnboardingWhatsappFailedRouteImport.update({
    id: '/whatsapp/failed',
    path: '/whatsapp/failed',
    getParentRoute: () => OnboardingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/whatsapp/failed': typeof OnboardingWhatsappFailedRoute
  '/onboarding/whatsapp/success': typeof OnboardingWhatsappSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/whatsapp/failed': typeof OnboardingWhatsappFailedRoute
  '/onboarding/whatsapp/success': typeof OnboardingWhatsappSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/whatsapp/failed': typeof OnboardingWhatsappFailedRoute
  '/onboarding/whatsapp/success': typeof OnboardingWhatsappSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/onboarding/whatsapp/failed'
    | '/onboarding/whatsapp/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/onboarding/whatsapp/failed'
    | '/onboarding/whatsapp/success'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/onboarding/whatsapp/failed'
    | '/onboarding/whatsapp/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/whatsapp/success': {
      id: '/onboarding/whatsapp/success'
      path: '/whatsapp/success'
      fullPath: '/onboarding/whatsapp/success'
      preLoaderRoute: typeof OnboardingWhatsappSuccessRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/whatsapp/failed': {
      id: '/onboarding/whatsapp/failed'
      path: '/whatsapp/failed'
      fullPath: '/onboarding/whatsapp/failed'
      preLoaderRoute: typeof OnboardingWhatsappFailedRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingWhatsappFailedRoute: typeof OnboardingWhatsappFailedRoute
  OnboardingWhatsappSuccessRoute: typeof OnboardingWhatsappSuccessRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingWhatsappFailedRoute: OnboardingWhatsappFailedRoute,
  OnboardingWhatsappSuccessRoute: OnboardingWhatsappSuccessRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
